# Generated by Django 5.0.2 on 2024-02-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='surname',
        ),
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(max_length=64, verbose_name='ФИО'),
        ),
    ]
