# Generated by Django 5.0.2 on 2024-02-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_analyzer', '0002_remove_expert_surname_alter_expert_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='total_mark',
            field=models.IntegerField(default=0, verbose_name='Итоговая оценка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'В процессе'), (1, 'Согласовано'), (-1, 'Дополнительная экспертиза')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
